# Site settings
title: Dan Salo's Blog
description: "An assortment of elegant Math and simple Code."
url: "http://dancsalo.github.io"
twitter_username: dancsalo
github_username:  dancsalo

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# SEO
twitter:
  username: dancsalo
facebook:
  publisher: 768300382
social:
  name: Dan Salo
  links:
    - https://twitter.com/dancsalo
    - https://www.facebook.com/dancsalo
    - https://www.linkedin.com/in/dancsalo
    - https://github.com/dancsalo

# Gems
gems:
- jekyll-seo-tag
